openapi: 3.0.3
info:
  title: Wallet - OpenAPI 3.0
  description: |-
    Wallet
  termsOfService: http://pagopa.it/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://wallet.pagopa.it/api/v1
tags:
  - name: Wallet
    description: Intercat with wallet
paths:
  /wallets:
    post:
      tags:
        - wallets
      summary: Add a new wallet
      description: Add a new wallet
      operationId: addWallet
      parameters:
        - in: header
          name: x-user-id
          schema:
            type: string
          required: true
      requestBody:
        description: Create a new wallet
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletPost'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletPostResponse'
        '405':
          description: Invalid input
  /wallets/{walletId}:
    put:
      tags:
        - wallets
      summary: Update an existing wallet
      description: Update an existing wallet by Id
      operationId: updateWallet
      parameters:
        - name: walletId
          in: path
          description: ID of wallet to return
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent wallet
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletUpdate'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletUpdateResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: wallet not found
        '405':
          description: Validation exception
    get:
      tags:
        - wallets
      summary: Find wallet by ID
      description: Returns a single pet
      operationId: getWalletById
      parameters:
        - name: walletId
          in: path
          description: ID of wallet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletUpdateResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Wallet not found
    delete:
      tags:
        - wallets
      summary: Deletes a wallet by ID
      description: delete a wallet
      operationId: deleteWallet
      parameters:
        - name: walletId
          in: path
          description: Wallet id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletDeleteResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Wallet not found
components:
  schemas:
    Wallet:
      type: object
      properties:
        paymentInstrumentId:
          type: string
    WalletPost:
      type: object
      properties:
        paymentInstrumentType:
          type: string
          enum: [ cards, paypal, bancomatpay ]
    WalletPostResponse:
      type: object
      properties:
        walletItemId:
          type: string
        logoutURI:
          type: string
    WalletUpdate:
      type: object
    WalletUpdateResponse:
      type: object
    WalletDeleteResponse:
      type: object
